### ISSUE TITLE
Cannot read properties of undefined (reading 'cookies')

### ISSUE THREAD

**Issue by SkySor44** [nuxt-community/supabase-module#26]
I'm having the same issue as @miguelramos in the closed issue he commented on: https://github.com/nuxt-community/supabase-module/issues/24#issuecomment-1095741230_:

`nuxt-config.ts`
```
supabase: {
    url: process.env.SUPABASE_URL,
    key: process.env.SUPABASE_KEY,
  },
  modules: ['@nuxtjs/supabase', '@pinia/nuxt'],
```

`"@supabase/supabase-js": "^1.33.3"`
`"@nuxtjs/supabase": "^0.1.7"`
`"nuxt3": "latest"`

Won't compile without a 500 error and:
```
[nitro] [request error] Cannot read properties of undefined (reading 'cookies')
  at Module.useSupabaseToken (./.nuxt/dist/server/server.mjs:8682:32)  
  at Module.useSupabaseClient (./.nuxt/dist/server/server.mjs:2937:39)  
  at ./.nuxt/dist/server/server.mjs:9123:40  
  at fn (./.nuxt/dist/server/server.mjs:350:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:352:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:307:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:317:11)  
  at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:44:7)  
  at async renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
```

**Comment by Atinux** [comment]
Can you update to latest Nuxt edge release and try again please @SkySor44 ?

See more context in https://github.com/nuxt/framework/pull/4283

Sorry about this issue, living on the edge might be dangerous :smile:

**Comment by miguelramos** [comment]
@Atinux it's ok.

**Comment by sduduzog** [comment]
Updating to latest didn't budge. I had to try version by version going back until I found one that works without the error which was `"nuxt3": "[3.0.0-27491748.3186841](https://www.npmjs.com/package/nuxt3/v/3.0.0-27491748.3186841)"`

**Comment by SkySor44** [comment]
Upgrading Nuxt3 fixed it for me! Thanks for the quick response time!

**Comment by KabooZ1987** [comment]
I still get the `Cannot read properties of undefined (reading 'cookies')`  when trying to authenticate.

is this the same or a similar problem, I'm on 0.1.7 of `@nuxtjs/supabase`
```
Nuxt CLI v3.0.0-27496606.e43ba6e                                                                                                                                                                   10:20:18
                                                                                                                                                                                                   10:20:18
  > Local:    http://localhost:3000/ 

ℹ Using Tailwind CSS from ~/node_modules/@nuxthq/ui/dist/runtime/tailwind.css                                                                                                     nuxt:tailwindcss 10:20:22
ℹ Vite client warmed up in 4297ms                                                                                                                                                                  10:20:28
ℹ Vite server warmed up in 1947ms                                                                                                                                                                  10:20:28
✔ Vite server built in 4213ms                                                                                                                                                                      10:20:30
✔ Nitro built in 475 ms                                                                                                                                                                      nitro 10:20:31
[nuxt] [request error] Cannot read properties of undefined (reading 'cookies')
  at session (./.nuxt/dev/index.mjs:493:41)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./node_modules/h3/dist/index.mjs:416:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:366:7)
```

**Comment by KabooZ1987** [comment]
Works now, thank you 😄
