### ISSUE TITLE
500 Error: init is not a function (Nuxt 3 RC5)

### ISSUE THREAD

**Issue by nddr** [nuxt-community/supabase-module#57]
### Version
@nuxtjs/supabase: v0.1.10 & 0.1.18
nuxt: 3 RC5

### Steps to reproduce
Update to Nuxt 3 RC5

### What is actually happening?
500
init is not a function

at Module.useState (./.nuxt/dist/server/server.mjs:1458:26)
at Module.useSupabaseUser (./.nuxt/dist/server/server.mjs:9992:53)
at ./.nuxt/dist/server/server.mjs:39938:38
at fn (./.nuxt/dist/server/server.mjs:899:27)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)
at callWithNuxt (./.nuxt/dist/server/server.mjs:901:23)
at applyPlugin (./.nuxt/dist/server/server.mjs:856:29)
at Module.applyPlugins (./.nuxt/dist/server/server.mjs:866:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)

**Comment by oripka** [comment]
I got the same error, now even if I set `"nuxt": "3.0.0-rc.4"` in package.json

**Comment by larbish** [comment]
Can you try with the last version of the module `v0.1.19` ? I did not reproduce in my projects. If not fixed, can you provide a reproduction ? 🙏

**Comment by nddr** [comment]
Hey @larbish, what is the best way to do a reproduction?

**Comment by larbish** [comment]
Hello @nddr, you can try on [stackblitz](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=README.md) or using [codesandbox](https://codesandbox.io/s/github/nuxt/starter/tree/v3-codesandbox) starters.

**Comment by nddr** [comment]
Thanks @larbish. I could not reproduce, so I updated my node to latest LTS (16.16), and re-installed node_modules and now it is working!
